### ISSUE TITLE
Where to put startup script :) ?

### ISSUE THREAD

**Issue by danalexilewis** [agentlewis/dinos#2]
@ahdinosaur Still trying to work out this monster you have created.

I have a single line that is for setting the speed of the lenovo push-stick to max. 

It creates the right setting based on a tmpfile that I created on my machine - this was the easiest way I could find of just getting it to work better.

file contents:

```
➜  ~ cd /etc/tmpfiles.d 
➜  tmpfiles.d l
total 24K
drwxr-xr-x   2 root root 4.0K Aug 31 14:39 .
drwxr-xr-x 137 root root  12K Oct 15 17:46 ..
-rw-r--r--   1 root root  234 Aug 31 14:25 tpoint.conf
-rw-r--r--   1 root root  130 Aug 31 14:39 trackpoint.conf
➜  tmpfiles.d cat tpoint.conf 
w /sys/devices/platform/i8042/serio1/speed - - - - 255
w /sys/devices/platform/i8042/serio1/sensitivity - - - - 255
w /sys/devices/platform/i8042/serio1/inertia - - - - 6
w /sys/devices/platform/i8042/serio1/press_to_select - - - - 0
➜  tmpfiles.d cat trackpoint.conf 
w /sys/devices/platform/i8042/serio1/serio2/speed - - - - 255
w /sys/devices/platform/i8042/serio1/serio2/sensitivity - - - - 255
```

command:

```
sudo systemd-tmpfiles --prefix=/sys --create 
```

So I have two TODOS:

 - [ ] add tpoint.conf and trackpoint.conf to dyno (plugin?)
 - [ ] add command to list of startup script to run on load

Can you give me some high level guidance of where to go :)

**Comment by ahdinosaur** [comment]
> add tpoint.conf and trackpoint.conf to dyno (plugin?)

something like https://github.com/ahdinosaur/dinos/blob/master/config/debian/index.js#L9, so you can create a file with the contents owned as root

> add command to list of startup script to run on load

if you need the startup script to run as root, you want to create a systemd startup script. see something like https://unix.stackexchange.com/questions/47695/how-to-write-startup-script-for-systemd#47715.

if the script doesn't need to run as root, you could put the script in `~/bin` and autostart it with KDE: https://docs.kde.org/trunk5/en/kde-workspace/kcontrol/autostart/index.html. this can be done through the settings page, something something autostart. i have redshift starting automatically with this, but haven't yet added this to `dinos`.

**Comment by danalexilewis** [comment]
Solved using a rules file following this guide: https://askubuntu.com/posts/761504/revisions
